sudo: required
dist: trusty
language: python
python:
  - "3.2"
  - "3.6"
before_install:
  - sudo apt-get -y install erlang
install: "pip install -r requirements.txt"
script:
  - python setup.py install
  - make tests
